### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dotnize** [dotnize/svaro#1]
### misc

- [ ] restructure to monorepo
- [ ] docs with sveltepress or starlight?
- [ ] write tests
- [ ] minimal sveltekit example with saving & loading data

## 0.1

- [ ] Core components
  - [x] Component list
  - [x] Canvas
  - [x] Property editor
  - [ ] Outline
- [ ] Editable fields/properties
  - [x] Text
  - [ ] Textarea
  - [x] Color
  - [x] Number
  - [ ] Boolean/checkbox
  - [ ] Radio
  - [ ] Select
  - [ ] Array/list
- [x] Initial json data structure for output (inspired by [react-from-json](https://github.com/measuredco/react-from-json))
- [ ] `<Render />`
- [ ] code cleanup, check improper usage of runes/unnecessary reactive state

## soon™

- [ ] #2
- [ ] #3
- [ ] #4
- [ ] Custom property types
- [ ] Component categories
- [ ] Configurable drag preview/morph
- [ ] Dynamic props & fields
- [ ] Load external data
- [ ] iframe support for dynamic viewport previews
- [ ] Undo/redo history
